### ISSUE TITLE
don't work with sketch 3.8

### ISSUE THREAD

**Issue by SoufianeAbid** [avdgriendt/sketch-radial-progress-bar#2]
Hi 

It did not work with me !!

**Comment by SoufianeAbid** [comment]
When you press 'create' 
The window does not appear

**Comment by matthewfowles** [comment]
I'm having the same issue!

**Comment by avdgriendt** [comment]
I'm investigating this issue.

**Comment by avdgriendt** [comment]
Should be fixed now.

**Comment by SoufianeAbid** [comment]
it works without proplems
thsnk you :dancers:
